name: Pre Release
on:
  # push:
  #   branches:
  #     - rc
  workflow_dispatch:
jobs:
  pypi-publish:
    name: upload release to PyPI Test
    runs-on: ubuntu-latest
    environment:
      name: PyPI Test
      url: https://test.pypi.org/project/mlflow-oidc-auth/
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Make release
        id: release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            - @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package distributions to PyPI
        if: steps.release.outputs.new_release_published == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
